apiVersion: apps/v1
kind: Deployment
metadata:
  name: mark1
  namespace: development
spec:
  selector:
    matchLabels:
      app: mark1
  template:
    metadata:
      labels:
        app: mark1
    spec:
      containers:
      - name: mark1
        image: rizvimmall/mark1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: sehatqdockerkey
---
apiVersion: v1
kind: Service
metadata:
  name: mark1
  namespace: development
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  mark1_mapping
      prefix: /dev6/go/
      rewrite: ""
      service: mark1.development:8080
spec:
  selector:
    app: mark1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


