apiVersion: apps/v1
kind: Deployment
metadata:
  name: mark1
  namespace: dev
spec:
  selector:
    matchLabels:
      app: mark1
  template:
    metadata:
      labels:
        app: mark1
    spec:
      containers:
      - name: mark1
        image: rizvimmall/mark1:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mark1
  namespace: dev
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: mark1
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: dev
  name: mark1-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: mark1
          servicePort: 8080
